server:
  port: 9000
  servlet:
    context-path: /myShop
    session:
      tracking-modes: cookie
spring:
  profiles:
    active:
      - database
  servlet:
    multipart:
      max-request-size: 60MB
      max-file-size: 50MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.myShop.**

springdoc:
  swagger-ui:
    path: /swagger
    csrf:
      enabled: true
  api-docs:
    path: /api-docs

logging:
  level:
    product: TRACE